### ISSUE TITLE
Configure custom type for worker

### ISSUE THREAD

**Issue by urbanisierung** [camunda-community-hub/zeebe-http-worker#35]
Currently the type for which the worker is registered is not configurable and set to `http`. In some use cases it would be useful to set a custom type.

The worker name is already configurable via the environment variable `ZEEBE_WORKER_NAME`. The same approach would fit to set the worker type with a new env var `ZEEBE_WORKER_TYPE`.

**Comment by berndruecker** [comment]
Make sense for me. I can most probably look at it next week

**Comment by berndruecker** [comment]
I introduce this new property:

`zeebe.worker.defaultType` or via respective environment variable `ZEEBE_WORKER_DEFAULTTYPE`

Please note that I adjusted the worker name accordingly - so it did change to  `ZEEBE_WORKER_DEFAULTNAME`

This change will leverage a new Spring Zeebe version that is based on Zeebe 0.22.0

**Comment by jwulf** [comment]
Can we make this an array, so that all code / tutorial examples that make use of `CAMUNDA_HTTP` still work? We are generating tutorials and examples now using this, and it would be best if they didn't rot. Also, users are deploying workflows using this task type.

It does make more sense on Camunda Cloud to use `ZEEBE-HTTP` as the task type, as explaining it in docs at the moment is: 

**Before** 

* Configure the service task Type to be `CAMUNDA-HTTP`. This will be serviced by the [Zeebe HTTP Worker](https://github.com/zeebe-io/zeebe-http-worker) in Camunda Cloud.

And would be better as: 

**After**

* Configure the service task Type to be `ZEEBE-HTTP`. This will be serviced by the [Zeebe HTTP Worker](https://github.com/zeebe-io/zeebe-http-worker) in Camunda Cloud.

**Comment by jwulf** [comment]
This env var `ZEEBE_WORKER_DEFAULTTYPE` may be misnamed: it looks like it is not the "default" type, but the **actual** task type - in which case a more accurate name would be `ZEEBE_WORKER_TASKTYPE`.

See here: https://forum.zeebe.io/t/http-worker-not-working/1010

**Comment by berndruecker** [comment]
I would say best create a new issue to address the different issues with the worker.
